version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - /home/lg/repos/lgcursos/Coursera2022/DataScience-Specialization/03-Cleaning-Data/mysql/volume/:/school.sql
